### ISSUE TITLE
lede config anpassen

### ISSUE THREAD

**Issue by fsteinel** [freifunk-kiel/site-ffki#2]
für bleeding edge gluon (aka LEDE) muss die site.conf angepasst werden.

Laut Flensburg sind das folgende commits
https://github.com/freifunk-flensburg/site-fffl/commit/fbf9c28301e3ba61c37d345439586cd1276888f3
https://github.com/freifunk-flensburg/site-fffl/commit/70d38c8551ab97a0d7d0f3103cd38cc648c32598
diese commit schalten aber 802.11 an ?
Ob diese auch das Problem 
```
gluon-SITE_CODE-2016.2.2~exp1612221211-tp-link-tl-wr842n-nd-v3.bin
```
des SITE_CODE im Dateinamen beheben indem da ffki steht?

**Comment by rubo77** [comment]
Ist im `lede` branch
