### ISSUE TITLE
DSGVO gerechter config mode

### ISSUE THREAD

**Issue by rubo77** [freifunk-kiel/site-ffki#21]
habe mal einen datenschutzlink eingebaut in unsere Firmware: https://github.com/freifunk-kiel/site-ffki/commit/11dba734b5f0c2e09dc0416217961cde2ab38f7c
ist das so ausreichend?

ev. muss hier noch was ergänzt werden? 

https://github.com/freifunk-gluon/gluon/blob/68ee56b86945025e359f93900f79ca912dfd3fea/package/gluon-config-mode-contact-info/i18n/de.po#L21

und hier
https://github.com/freifunk-kiel/ffki-packages/commit/74289f173a24eced5655a8c087f4ed711f6643a5

**Comment by rubo77** [comment]
**bigfoot:**

>Damit hast du schon mal die verarbeitungserlaubnis. Fehlt noch ein kontakt wo derjenige seine daten ändern bzw. löschen lassen kann.
>Am besten ein Link zu einer Freifunk Kiel seite - wo mehr info zum Datenschutz und verantworlichen steht.

**Comment by rubo77** [comment]
Diesen Text können wir auch bei uns schon einbauen:

https://github.com/freifunk-gluon/gluon/pull/1394/files

**Comment by sargon** [comment]
Schau doch bitte mal auf den PR hier. Wenn ich das richtig sehe tun die schon so ziemlich alles was man DSGVO mässig machen muss. Das wurde auf der WCW18 entwickelt.
https://github.com/freifunk-gluon/gluon/pull/1394

**Comment by rubo77** [comment]
@sargon das ist ja genau die Text Änderung die ich meinte

**Comment by rubo77** [comment]
habe den text mal ergänzt hier: https://github.com/freifunk-kiel/site-ffki/commit/ac619dd2308ff100e89fc0d6126566cb72896cc7

**Comment by rubo77** [comment]
Denke inzwischen ist das überall OK
