### ISSUE TITLE
Firmware testen 2018.1.1-461

### ISSUE THREAD

**Issue by rubo77** [freifunk-kiel/site-ffki#22]
1. Grund-Test

   - [x] Testen ob der richtige autoupdater Branch eingestellt ist, wenn man einen Router neu flasht
   - [ ] Sind alle Texte im Config mode korrekt? (Auch der angezeigte Text beim reboot mit disableten Mesh-VPN)
   - [x] Autoupdater Test: Version in `/lib/gluon/releases` von Hand runter setzen und `autoupdater -f` aufrufen
      - [x] direkt am Uplink
      - [x] als mesh-only Knoten

2. meshvpn Test, 

   - [x] Test ob richtige IPv6 und passsende IPv4 verteilt wird.
   - [x] DNS testen intern/extern
   - [x] 1. NTP Server Testen ob die Zeiten stimmen und v4 so wie v6 erreichbar (kann 20min. dauern)

3. Mesh Test

   - [x] wifi
   - [x] mol
   - [x] mow
   - [x] mol nach mow

Jeweils die Erreichbarkeit von DNS intern/extern so wie NTP testen

4. Custom Packages Test

   - [ ] alle custom packages Einstellungen der Configseiten testen und schauen ob sie auch wirklich nach dem Reboot erhalten bleiben
   - [ ] alle Taster Funktionen testen: https://github.com/rubo77/ffm-packages/issues/2

5. Stabilität

   - [ ] gibt es reboots?
      - [ ] durch quickfix (Einträge im quickfix log)
      - [ ] durch kernel freeze (wenn ja, lokal per ssh verbinden und das log laufen lassen bis er abschmiert) 
   - [ ] Load beobachten in der Statuspage oder besser mit `top` , bzw. im Grafana

 
Angelehnt an https://github.com/Freifunk-Nord/nord-site/issues/23

**Comment by TobleMiner** [comment]
1. Basics:
 - Branch: Ok
 - Config mode: Ungetestet
 - Autoupdater: Ohne Uplink ok

2. meshvpn:
 - IPv6: ok
 - IPv4: ok
 - DNS: ok
 - NTP: ok

3. mesh:
 - Wifi: Ungetestet
 - MoL: Ungetestet
 - MoW: Ok
 - MoL + MoW: Ungetestet

4. Custom packages:
 - alles testen: Ungetestet
 - Taster: Ungetestet

5. Reboots:
 - Reboots: Nein, nicht mehr als vorher
 - Load: Bei mir schon länger immer ok

**Comment by sargon** [comment]
Basics:

    Branch: Ok
    Config mode: Ungetestet
    Autoupdater: Mit und Ohne Uplink ok

    meshvpn:

    IPv6: ok
    IPv4: ok
    DNS: ok
    NTP: ok

    mesh:

    Wifi: Getestet
    MoL: Getestet
    MoW: Ok
    MoL + MoW: Getestet

    Custom packages:

    alles testen: Ungetestet
    Taster: Ungetestet

    Reboots:

    Reboots: Nein, nicht mehr als vorher
    Load: Bei mir schon länger immer ok

**Comment by TobleMiner** [comment]
Scheint nicht zu brennen
